name: Create PDF

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get install -y cm-super \
                                  texlive-xetex \
                                  texlive-latex-extra \
                                  texlive-lang-cyrillic \
                                  texlive-science \
                                  texlive-pictures \
                                  fonts-texgyre \
                                  inkscape
          sudo fc-cache -fv 

      - name: Build PDF
        run: |
          latexmk -xelatex -f -synctex=1 -interaction=nonstopmode -file-line-error --shell-escape -jobname=practice_report practice_report.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4  
        with:
          name: practice_report.pdf  
          path: practice_report.pdf
