name: Create PDF

on:
  pull_request:
    branches:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies 
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full 
          sudo apt-get install -y ttf-mscorefonts-installer
          


      - name: Build PDF
        run: |
          xelatex -interaction=nonstopmode -halt-on-error practice_report.tex
          xelatex -interaction=nonstopmode -halt-on-error practice_report.tex  
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf
          path: practice_report.pdf
